import type { SubBrand, LauncherTheme, Language } from "@/types";

export const ADMIN_PASSWORD = "1122";

export const LANGUAGES: { code: Language; label: string; native: string; dir: "ltr" | "rtl" }[] = [
  { code: "en", label: "English", native: "English", dir: "ltr" },
  { code: "ur", label: "Urdu", native: "اردو", dir: "rtl" },
  { code: "ar", label: "Arabic", native: "عربي", dir: "rtl" },
  { code: "bn", label: "Bengali", native: "বাংলা", dir: "ltr" },
  { code: "fa", label: "Persian", native: "فارسی", dir: "rtl" },
  { code: "ru", label: "Russian", native: "Русский", dir: "ltr" },
  { code: "zh", label: "Chinese", native: "中文", dir: "ltr" },
  { code: "tr", label: "Turkish", native: "Türkçe", dir: "ltr" },
  { code: "ps", label: "Pashto", native: "پښتو", dir: "rtl" },
  { code: "hi", label: "Hindi", native: "हिन्दी", dir: "ltr" },
];

export const SUB_BRANDS: SubBrand[] = [
  {
    id: "unifeel",
    name: "UniFeel™",
    tagline: "Feel the World as One",
    description: "Emotional intelligence & community connection platform uniting hearts globally",
    icon: "💚",
    color: "text-emerald-700",
    glowColor: "#00c97a",
    bgGlass: "glass-emerald",
  },
  {
    id: "uniedge",
    name: "UniEdge™",
    tagline: "Your Competitive Edge",
    description: "Advanced analytics, insights and competitive intelligence for forward thinkers",
    icon: "⚡",
    color: "text-yellow-700",
    glowColor: "#ffd700",
    bgGlass: "glass-gold",
  },
  {
    id: "uninews",
    name: "UniNews™",
    tagline: "Truth Without Borders",
    description: "Real-time multilingual news aggregation with verified global sources",
    icon: "📰",
    color: "text-blue-700",
    glowColor: "#0066ff",
    bgGlass: "glass-white",
  },
  {
    id: "unispark",
    name: "UniSpark™",
    tagline: "Ignite Innovation",
    description: "Creative studio and innovation hub for visionaries and entrepreneurs",
    icon: "✨",
    color: "text-purple-700",
    glowColor: "#8b5cf6",
    bgGlass: "glass-white",
  },
  {
    id: "unimail",
    name: "UniMail™",
    tagline: "Universal Secure Mail",
    description: "Encrypted, multilingual communication system for seamless global connectivity",
    icon: "✉️",
    color: "text-crimson-deep",
    glowColor: "#e8003d",
    bgGlass: "glass-crimson",
  },
  {
    id: "unihost",
    name: "UniHost™",
    tagline: "Host the World",
    description: "Premium global hosting infrastructure with 24/7 uptime and edge CDN",
    icon: "🌐",
    color: "text-teal-700",
    glowColor: "#0d9488",
    bgGlass: "glass-emerald",
  },
];

export const LAUNCHER_THEMES: LauncherTheme[] = [
  {
    id: "emerald-crystal",
    name: "Emerald Crystal",
    description: "Luminous emerald glass with crystal-clear white surfaces",
    primaryColor: "#007a4a",
    accentColor: "#00c97a",
    bgStyle: "bg-gradient-to-br from-white via-emerald-50 to-green-50",
    textStyle: "text-emerald-800",
  },
  {
    id: "crimson-flame",
    name: "Crimson Flame",
    description: "Passionate crimson gradients with fiery glow effects",
    primaryColor: "#9b0028",
    accentColor: "#e8003d",
    bgStyle: "bg-gradient-to-br from-white via-red-50 to-rose-50",
    textStyle: "text-red-900",
  },
  {
    id: "royal-gold",
    name: "Royal Gold",
    description: "Majestic golden radiance on pristine white",
    primaryColor: "#b8860b",
    accentColor: "#ffd700",
    bgStyle: "bg-gradient-to-br from-white via-yellow-50 to-amber-50",
    textStyle: "text-yellow-900",
  },
  {
    id: "cosmic-prism",
    name: "Cosmic Prism",
    description: "Multi-spectrum prismatic light refractions",
    primaryColor: "#4f46e5",
    accentColor: "#818cf8",
    bgStyle: "bg-gradient-to-br from-white via-indigo-50 to-violet-50",
    textStyle: "text-indigo-900",
  },
  {
    id: "ocean-deep",
    name: "Ocean Deep",
    description: "Deep ocean blues with luminous aqua highlights",
    primaryColor: "#0369a1",
    accentColor: "#0ea5e9",
    bgStyle: "bg-gradient-to-br from-white via-sky-50 to-blue-50",
    textStyle: "text-sky-900",
  },
  {
    id: "midnight-aurora",
    name: "Midnight Aurora",
    description: "Northern lights palette on deep sapphire night",
    primaryColor: "#064e3b",
    accentColor: "#34d399",
    bgStyle: "bg-gradient-to-br from-slate-900 via-emerald-950 to-slate-800",
    textStyle: "text-emerald-300",
  },
  {
    id: "pure-platinum",
    name: "Pure Platinum",
    description: "Minimalist platinum-white with ultra-clean lines",
    primaryColor: "#374151",
    accentColor: "#9ca3af",
    bgStyle: "bg-gradient-to-br from-white via-gray-50 to-slate-50",
    textStyle: "text-gray-900",
  },
  {
    id: "triune-glory",
    name: "Triune Glory™",
    description: "Signature SMART WORLD ORDER emerald-gold-crimson trinity",
    primaryColor: "#007a4a",
    accentColor: "#ffd700",
    bgStyle: "bg-gradient-to-br from-white via-emerald-50 to-red-50",
    textStyle: "text-emerald-900",
  },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    platform_name: "SMART WORLD ORDER™",
    tagline: "ESOneWorld™ — A Global Family Platform",
    vision_by: "A Vision by Dr M Irfan Qadir Thaheem",
    welcome: "Welcome to the Future",
    explore: "Explore Platform",
    admin_panel: "Admin Panel",
    theme_light: "Light Mode",
    theme_dark: "Dark Mode",
    language: "Language",
    about: "About Us",
    legal: "Legal",
    privacy: "Privacy Policy",
    copyright: "Copyright",
    disclaimer: "Disclaimer",
    mission: "Our Mission",
    contact: "Contact",
    launchers: "Launchers",
    left_panel: "Left Panel",
    right_panel: "Right Panel",
    sub_brands: "Platform Brands",
    features: "Features",
    settings: "Settings",
    logout: "Logout",
    login: "Login",
    password: "Password",
    enter_password: "Enter Admin Password",
    wrong_password: "Incorrect password. Access denied.",
    admin_welcome: "Welcome, Administrator",
    add_more: "Add More Features",
    section: "Section",
    enable: "Enable",
    disable: "Disable",
    delete: "Delete",
    rename: "Rename",
    replace: "Replace",
    publish: "Publish",
    save: "Save",
    cancel: "Cancel",
    saved: "Auto-Saved",
    synced: "Synced",
  },
  ur: {
    platform_name: "سمارٹ ورلڈ آرڈر™",
    tagline: "ای ایس ون ورلڈ™ — ایک عالمی خاندانی پلیٹ فارم",
    vision_by: "ڈاکٹر محمد عرفان قادر طاہم کا وژن",
    welcome: "مستقبل میں خوش آمدید",
    explore: "پلیٹ فارم دریافت کریں",
    admin_panel: "ایڈمن پینل",
    theme_light: "لائٹ موڈ",
    theme_dark: "ڈارک موڈ",
    language: "زبان",
    about: "ہمارے بارے میں",
    legal: "قانونی",
    privacy: "رازداری پالیسی",
    copyright: "کاپی رائٹ",
    disclaimer: "اعلامیہ",
    mission: "ہمارا مشن",
    contact: "رابطہ",
    launchers: "لانچرز",
    left_panel: "بائیں پینل",
    right_panel: "دائیں پینل",
    sub_brands: "پلیٹ فارم برانڈز",
    features: "خصوصیات",
    settings: "ترتیبات",
    logout: "لاگ آؤٹ",
    login: "لاگ ان",
    password: "پاسورڈ",
    enter_password: "ایڈمن پاسورڈ درج کریں",
    wrong_password: "غلط پاسورڈ۔ رسائی مسترد۔",
    admin_welcome: "خوش آمدید، ایڈمن",
    add_more: "مزید خصوصیات شامل کریں",
    section: "سیکشن",
    enable: "فعال",
    disable: "غیر فعال",
    delete: "حذف",
    rename: "نام تبدیل",
    replace: "تبدیل",
    publish: "شائع",
    save: "محفوظ",
    cancel: "منسوخ",
    saved: "خودکار محفوظ",
    synced: "ہم آہنگ",
  },
  ar: {
    platform_name: "النظام العالمي الذكي™",
    tagline: "ای اس ون ورلڈ™ — منصة الأسرة العالمية",
    vision_by: "رؤية الدكتور محمد عرفان قادر طاهم",
    welcome: "مرحباً بالمستقبل",
    explore: "استكشف المنصة",
    admin_panel: "لوحة الإدارة",
    theme_light: "الوضع المضيء",
    theme_dark: "الوضع الداكن",
    language: "اللغة",
    about: "من نحن",
    legal: "قانوني",
    privacy: "سياسة الخصوصية",
    copyright: "حقوق الطبع",
    disclaimer: "إخلاء المسؤولية",
    mission: "مهمتنا",
    contact: "اتصل بنا",
    launchers: "المشغلات",
    left_panel: "اللوحة اليسرى",
    right_panel: "اللوحة اليمنى",
    sub_brands: "علامات المنصة",
    features: "المميزات",
    settings: "الإعدادات",
    logout: "تسجيل خروج",
    login: "تسجيل دخول",
    password: "كلمة المرور",
    enter_password: "أدخل كلمة مرور المسؤول",
    wrong_password: "كلمة مرور خاطئة. تم رفض الوصول.",
    admin_welcome: "مرحباً، المسؤول",
    add_more: "إضافة المزيد",
    section: "قسم",
    enable: "تفعيل",
    disable: "تعطيل",
    delete: "حذف",
    rename: "إعادة تسمية",
    replace: "استبدال",
    publish: "نشر",
    save: "حفظ",
    cancel: "إلغاء",
    saved: "محفوظ تلقائياً",
    synced: "متزامن",
  },
  bn: { platform_name: "স্মার্ট ওয়ার্ল্ড অর্ডার™", tagline: "ESOneWorld™ — একটি বৈশ্বিক পারিবারিক প্ল্যাটফর্ম", vision_by: "ড. এম ইরফান কাদির থাহেমের দৃষ্টিভঙ্গি", welcome: "ভবিষ্যতে স্বাগতম", explore: "প্ল্যাটফর্ম অন্বেষণ করুন", admin_panel: "অ্যাডমিন প্যানেল", theme_light: "লাইট মোড", theme_dark: "ডার্ক মোড", language: "ভাষা", about: "আমাদের সম্পর্কে", legal: "আইনি", privacy: "গোপনীয়তা নীতি", copyright: "কপিরাইট", disclaimer: "দাবিত্যাগ", mission: "আমাদের মিশন", contact: "যোগাযোগ", launchers: "লঞ্চার", left_panel: "বাম প্যানেল", right_panel: "ডান প্যানেল", sub_brands: "প্ল্যাটফর্ম ব্র্যান্ড", features: "বৈশিষ্ট্য", settings: "সেটিংস", logout: "লগআউট", login: "লগইন", password: "পাসওয়ার্ড", enter_password: "অ্যাডমিন পাসওয়ার্ড দিন", wrong_password: "ভুল পাসওয়ার্ড।", admin_welcome: "স্বাগতম, প্রশাসক", add_more: "আরো যোগ করুন", section: "বিভাগ", enable: "সক্ষম", disable: "অক্ষম", delete: "মুছুন", rename: "নাম পরিবর্তন", replace: "প্রতিস্থাপন", publish: "প্রকাশ", save: "সংরক্ষণ", cancel: "বাতিল", saved: "স্বতঃসংরক্ষিত", synced: "সিঙ্ক্রোনাইজড" },
  fa: { platform_name: "نظم جهانی هوشمند™", tagline: "ESOneWorld™ — پلتفرم خانواده جهانی", vision_by: "چشم‌انداز دکتر م عرفان قادر طاهم", welcome: "به آینده خوش آمدید", explore: "کاوش در پلتفرم", admin_panel: "پنل مدیریت", theme_light: "حالت روشن", theme_dark: "حالت تاریک", language: "زبان", about: "درباره ما", legal: "قانونی", privacy: "سیاست حریم خصوصی", copyright: "حق مؤلف", disclaimer: "سلب مسئولیت", mission: "مأموریت ما", contact: "تماس", launchers: "لانچرها", left_panel: "پنل چپ", right_panel: "پنل راست", sub_brands: "برندهای پلتفرم", features: "ویژگی‌ها", settings: "تنظیمات", logout: "خروج", login: "ورود", password: "رمز عبور", enter_password: "رمز مدیریت را وارد کنید", wrong_password: "رمز اشتباه است.", admin_welcome: "خوش آمدید، مدیر", add_more: "افزودن بیشتر", section: "بخش", enable: "فعال", disable: "غیرفعال", delete: "حذف", rename: "تغییر نام", replace: "جایگزینی", publish: "انتشار", save: "ذخیره", cancel: "لغو", saved: "ذخیره خودکار", synced: "همگام‌سازی شد" },
  ru: { platform_name: "УМНЫЙ МИРОВОЙ ПОРЯДОК™", tagline: "ESOneWorld™ — Глобальная семейная платформа", vision_by: "Видение д-ра М Ирфан Кадир Тахима", welcome: "Добро пожаловать в будущее", explore: "Исследовать платформу", admin_panel: "Панель администратора", theme_light: "Светлая тема", theme_dark: "Тёмная тема", language: "Язык", about: "О нас", legal: "Правовой", privacy: "Политика конфиденциальности", copyright: "Авторское право", disclaimer: "Отказ от ответственности", mission: "Наша миссия", contact: "Контакт", launchers: "Лаунчеры", left_panel: "Левая панель", right_panel: "Правая панель", sub_brands: "Бренды платформы", features: "Функции", settings: "Настройки", logout: "Выход", login: "Вход", password: "Пароль", enter_password: "Введите пароль администратора", wrong_password: "Неверный пароль.", admin_welcome: "Добро пожаловать, Администратор", add_more: "Добавить больше", section: "Раздел", enable: "Включить", disable: "Отключить", delete: "Удалить", rename: "Переименовать", replace: "Заменить", publish: "Опубликовать", save: "Сохранить", cancel: "Отмена", saved: "Автосохранено", synced: "Синхронизировано" },
  zh: { platform_name: "智慧世界秩序™", tagline: "ESOneWorld™ — 全球家庭平台", vision_by: "伊尔凡·卡迪尔·塔希姆博士的愿景", welcome: "欢迎来到未来", explore: "探索平台", admin_panel: "管理面板", theme_light: "亮色模式", theme_dark: "暗色模式", language: "语言", about: "关于我们", legal: "法律", privacy: "隐私政策", copyright: "版权", disclaimer: "免责声明", mission: "我们的使命", contact: "联系", launchers: "启动器", left_panel: "左侧面板", right_panel: "右侧面板", sub_brands: "平台品牌", features: "功能", settings: "设置", logout: "退出", login: "登录", password: "密码", enter_password: "输入管理员密码", wrong_password: "密码错误。", admin_welcome: "欢迎，管理员", add_more: "添加更多", section: "部分", enable: "启用", disable: "禁用", delete: "删除", rename: "重命名", replace: "替换", publish: "发布", save: "保存", cancel: "取消", saved: "已自动保存", synced: "已同步" },
  tr: { platform_name: "AKILLI DÜNYA DÜZENİ™", tagline: "ESOneWorld™ — Küresel Aile Platformu", vision_by: "Dr M İrfan Kadir Tahim'in Vizyonu", welcome: "Geleceğe Hoş Geldiniz", explore: "Platformu Keşfet", admin_panel: "Yönetici Paneli", theme_light: "Açık Mod", theme_dark: "Koyu Mod", language: "Dil", about: "Hakkımızda", legal: "Yasal", privacy: "Gizlilik Politikası", copyright: "Telif Hakkı", disclaimer: "Sorumluluk Reddi", mission: "Misyonumuz", contact: "İletişim", launchers: "Başlatıcılar", left_panel: "Sol Panel", right_panel: "Sağ Panel", sub_brands: "Platform Markaları", features: "Özellikler", settings: "Ayarlar", logout: "Çıkış", login: "Giriş", password: "Şifre", enter_password: "Yönetici şifresini girin", wrong_password: "Yanlış şifre.", admin_welcome: "Hoş Geldiniz, Yönetici", add_more: "Daha Fazla Ekle", section: "Bölüm", enable: "Etkinleştir", disable: "Devre Dışı", delete: "Sil", rename: "Yeniden Adlandır", replace: "Değiştir", publish: "Yayınla", save: "Kaydet", cancel: "İptal", saved: "Otomatik Kaydedildi", synced: "Senkronize" },
  ps: { platform_name: "هوښیار نړیوال نظم™", tagline: "ESOneWorld™ — نړیواله کورنۍ پلیټفارم", vision_by: "د ډاکتر م عرفان قادر طاهم لید", welcome: "راتلونکي ته ښه راغلاست", explore: "پلیټفارم وپلټئ", admin_panel: "مدیر پینل", theme_light: "رڼا حالت", theme_dark: "تیاره حالت", language: "ژبه", about: "زموږ په اړه", legal: "قانوني", privacy: "د محرمیت پالیسي", copyright: "کاپي رایټ", disclaimer: "مسؤلیت", mission: "زموږ ماموریت", contact: "اړیکه", launchers: "لانچرونه", left_panel: "کیڼ پینل", right_panel: "ښي پینل", sub_brands: "د پلیټفارم برانډونه", features: "ځانګړتیاوې", settings: "ترتیبات", logout: "وتل", login: "ننوتل", password: "پاسورډ", enter_password: "د مدیر پاسورډ ولیکئ", wrong_password: "غلط پاسورډ.", admin_welcome: "ښه راغلاست، مدیر", add_more: "نور اضافه کړئ", section: "برخه", enable: "فعال", disable: "غیر فعال", delete: "ړنګول", rename: "نوم بدلول", replace: "بدلول", publish: "خپرول", save: "خوندي کول", cancel: "لغوه", saved: "اتوماتیک خوندي", synced: "همغږي" },
  hi: { platform_name: "स्मार्ट वर्ल्ड ऑर्डर™", tagline: "ESOneWorld™ — एक वैश्विक परिवार प्लेटफ़ॉर्म", vision_by: "डॉ एम इरफ़ान क़ादिर ताहिम का दृष्टिकोण", welcome: "भविष्य में आपका स्वागत है", explore: "प्लेटफ़ॉर्म देखें", admin_panel: "व्यवस्थापक पैनल", theme_light: "लाइट मोड", theme_dark: "डार्क मोड", language: "भाषा", about: "हमारे बारे में", legal: "कानूनी", privacy: "गोपनीयता नीति", copyright: "कॉपीराइट", disclaimer: "अस्वीकरण", mission: "हमारा मिशन", contact: "संपर्क", launchers: "लॉन्चर", left_panel: "बायाँ पैनल", right_panel: "दायाँ पैनल", sub_brands: "प्लेटफ़ॉर्म ब्रांड", features: "विशेषताएँ", settings: "सेटिंग्स", logout: "लॉगआउट", login: "लॉगिन", password: "पासवर्ड", enter_password: "व्यवस्थापक पासवर्ड दर्ज करें", wrong_password: "गलत पासवर्ड।", admin_welcome: "स्वागत है, व्यवस्थापक", add_more: "और जोड़ें", section: "अनुभाग", enable: "सक्षम", disable: "अक्षम", delete: "हटाएं", rename: "नाम बदलें", replace: "बदलें", publish: "प्रकाशित", save: "सहेजें", cancel: "रद्द", saved: "स्वतः सहेजा गया", synced: "सिंक्रोनाइज़ड" },
};
